/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SlaveServer_H
#define SlaveServer_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "slave_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class SlaveServerIf {
 public:
  virtual ~SlaveServerIf() {}
  virtual void initQubits( ::InitQubitsResp& _return, const  ::InitQubitsReq& req) = 0;
  virtual void sendCircuitCmd( ::SendCircuitCmdResp& _return, const  ::SendCircuitCmdReq& req) = 0;
  virtual void cancelCmd( ::CancelCmdResp& _return, const  ::CancelCmdReq& req) = 0;
  virtual void getProbAmp( ::GetProbAmpResp& _return, const  ::GetProbAmpReq& req) = 0;
  virtual void getProbOfOutcome( ::GetProbOfOutcomeResp& _return, const  ::GetProbOfOutcomeReq& req) = 0;
  virtual void getProbOfAllOutcome( ::GetProbOfAllOutcomResp& _return, const  ::GetProbOfAllOutcomReq& req) = 0;
  virtual void getAllState( ::GetAllStateResp& _return, const  ::GetAllStateReq& req) = 0;
  virtual void run( ::RunCircuitResp& _return, const  ::RunCircuitReq& req) = 0;
  virtual void applyQFT( ::ApplyQFTResp& _return, const  ::ApplyQFTReq& req) = 0;
  virtual void applyFullQFT( ::ApplyFullQFTResp& _return, const  ::ApplyFullQFTReq& req) = 0;
  virtual void getExpecPauliProd( ::GetExpecPauliProdResp& _return, const  ::GetExpecPauliProdReq& req) = 0;
  virtual void getExpecPauliSum( ::GetExpecPauliSumResp& _return, const  ::GetExpecPauliSumReq& req) = 0;
};

class SlaveServerIfFactory {
 public:
  typedef SlaveServerIf Handler;

  virtual ~SlaveServerIfFactory() {}

  virtual SlaveServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SlaveServerIf* /* handler */) = 0;
  };

class SlaveServerIfSingletonFactory : virtual public SlaveServerIfFactory {
 public:
  SlaveServerIfSingletonFactory(const ::std::shared_ptr<SlaveServerIf>& iface) : iface_(iface) {}
  virtual ~SlaveServerIfSingletonFactory() {}

  virtual SlaveServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(SlaveServerIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<SlaveServerIf> iface_;
};

class SlaveServerNull : virtual public SlaveServerIf {
 public:
  virtual ~SlaveServerNull() {}
  void initQubits( ::InitQubitsResp& /* _return */, const  ::InitQubitsReq& /* req */) override {
    return;
  }
  void sendCircuitCmd( ::SendCircuitCmdResp& /* _return */, const  ::SendCircuitCmdReq& /* req */) override {
    return;
  }
  void cancelCmd( ::CancelCmdResp& /* _return */, const  ::CancelCmdReq& /* req */) override {
    return;
  }
  void getProbAmp( ::GetProbAmpResp& /* _return */, const  ::GetProbAmpReq& /* req */) override {
    return;
  }
  void getProbOfOutcome( ::GetProbOfOutcomeResp& /* _return */, const  ::GetProbOfOutcomeReq& /* req */) override {
    return;
  }
  void getProbOfAllOutcome( ::GetProbOfAllOutcomResp& /* _return */, const  ::GetProbOfAllOutcomReq& /* req */) override {
    return;
  }
  void getAllState( ::GetAllStateResp& /* _return */, const  ::GetAllStateReq& /* req */) override {
    return;
  }
  void run( ::RunCircuitResp& /* _return */, const  ::RunCircuitReq& /* req */) override {
    return;
  }
  void applyQFT( ::ApplyQFTResp& /* _return */, const  ::ApplyQFTReq& /* req */) override {
    return;
  }
  void applyFullQFT( ::ApplyFullQFTResp& /* _return */, const  ::ApplyFullQFTReq& /* req */) override {
    return;
  }
  void getExpecPauliProd( ::GetExpecPauliProdResp& /* _return */, const  ::GetExpecPauliProdReq& /* req */) override {
    return;
  }
  void getExpecPauliSum( ::GetExpecPauliSumResp& /* _return */, const  ::GetExpecPauliSumReq& /* req */) override {
    return;
  }
};

typedef struct _SlaveServer_initQubits_args__isset {
  _SlaveServer_initQubits_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_initQubits_args__isset;

class SlaveServer_initQubits_args {
 public:

  SlaveServer_initQubits_args(const SlaveServer_initQubits_args&);
  SlaveServer_initQubits_args& operator=(const SlaveServer_initQubits_args&);
  SlaveServer_initQubits_args() noexcept {
  }

  virtual ~SlaveServer_initQubits_args() noexcept;
   ::InitQubitsReq req;

  _SlaveServer_initQubits_args__isset __isset;

  void __set_req(const  ::InitQubitsReq& val);

  bool operator == (const SlaveServer_initQubits_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_initQubits_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_initQubits_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_initQubits_pargs {
 public:


  virtual ~SlaveServer_initQubits_pargs() noexcept;
  const  ::InitQubitsReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_initQubits_result__isset {
  _SlaveServer_initQubits_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_initQubits_result__isset;

class SlaveServer_initQubits_result {
 public:

  SlaveServer_initQubits_result(const SlaveServer_initQubits_result&);
  SlaveServer_initQubits_result& operator=(const SlaveServer_initQubits_result&);
  SlaveServer_initQubits_result() noexcept {
  }

  virtual ~SlaveServer_initQubits_result() noexcept;
   ::InitQubitsResp success;

  _SlaveServer_initQubits_result__isset __isset;

  void __set_success(const  ::InitQubitsResp& val);

  bool operator == (const SlaveServer_initQubits_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_initQubits_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_initQubits_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_initQubits_presult__isset {
  _SlaveServer_initQubits_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_initQubits_presult__isset;

class SlaveServer_initQubits_presult {
 public:


  virtual ~SlaveServer_initQubits_presult() noexcept;
   ::InitQubitsResp* success;

  _SlaveServer_initQubits_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_sendCircuitCmd_args__isset {
  _SlaveServer_sendCircuitCmd_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_sendCircuitCmd_args__isset;

class SlaveServer_sendCircuitCmd_args {
 public:

  SlaveServer_sendCircuitCmd_args(const SlaveServer_sendCircuitCmd_args&);
  SlaveServer_sendCircuitCmd_args& operator=(const SlaveServer_sendCircuitCmd_args&);
  SlaveServer_sendCircuitCmd_args() noexcept {
  }

  virtual ~SlaveServer_sendCircuitCmd_args() noexcept;
   ::SendCircuitCmdReq req;

  _SlaveServer_sendCircuitCmd_args__isset __isset;

  void __set_req(const  ::SendCircuitCmdReq& val);

  bool operator == (const SlaveServer_sendCircuitCmd_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_sendCircuitCmd_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_sendCircuitCmd_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_sendCircuitCmd_pargs {
 public:


  virtual ~SlaveServer_sendCircuitCmd_pargs() noexcept;
  const  ::SendCircuitCmdReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_sendCircuitCmd_result__isset {
  _SlaveServer_sendCircuitCmd_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_sendCircuitCmd_result__isset;

class SlaveServer_sendCircuitCmd_result {
 public:

  SlaveServer_sendCircuitCmd_result(const SlaveServer_sendCircuitCmd_result&);
  SlaveServer_sendCircuitCmd_result& operator=(const SlaveServer_sendCircuitCmd_result&);
  SlaveServer_sendCircuitCmd_result() noexcept {
  }

  virtual ~SlaveServer_sendCircuitCmd_result() noexcept;
   ::SendCircuitCmdResp success;

  _SlaveServer_sendCircuitCmd_result__isset __isset;

  void __set_success(const  ::SendCircuitCmdResp& val);

  bool operator == (const SlaveServer_sendCircuitCmd_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_sendCircuitCmd_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_sendCircuitCmd_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_sendCircuitCmd_presult__isset {
  _SlaveServer_sendCircuitCmd_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_sendCircuitCmd_presult__isset;

class SlaveServer_sendCircuitCmd_presult {
 public:


  virtual ~SlaveServer_sendCircuitCmd_presult() noexcept;
   ::SendCircuitCmdResp* success;

  _SlaveServer_sendCircuitCmd_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_cancelCmd_args__isset {
  _SlaveServer_cancelCmd_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_cancelCmd_args__isset;

class SlaveServer_cancelCmd_args {
 public:

  SlaveServer_cancelCmd_args(const SlaveServer_cancelCmd_args&);
  SlaveServer_cancelCmd_args& operator=(const SlaveServer_cancelCmd_args&);
  SlaveServer_cancelCmd_args() noexcept {
  }

  virtual ~SlaveServer_cancelCmd_args() noexcept;
   ::CancelCmdReq req;

  _SlaveServer_cancelCmd_args__isset __isset;

  void __set_req(const  ::CancelCmdReq& val);

  bool operator == (const SlaveServer_cancelCmd_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_cancelCmd_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_cancelCmd_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_cancelCmd_pargs {
 public:


  virtual ~SlaveServer_cancelCmd_pargs() noexcept;
  const  ::CancelCmdReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_cancelCmd_result__isset {
  _SlaveServer_cancelCmd_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_cancelCmd_result__isset;

class SlaveServer_cancelCmd_result {
 public:

  SlaveServer_cancelCmd_result(const SlaveServer_cancelCmd_result&);
  SlaveServer_cancelCmd_result& operator=(const SlaveServer_cancelCmd_result&);
  SlaveServer_cancelCmd_result() noexcept {
  }

  virtual ~SlaveServer_cancelCmd_result() noexcept;
   ::CancelCmdResp success;

  _SlaveServer_cancelCmd_result__isset __isset;

  void __set_success(const  ::CancelCmdResp& val);

  bool operator == (const SlaveServer_cancelCmd_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_cancelCmd_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_cancelCmd_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_cancelCmd_presult__isset {
  _SlaveServer_cancelCmd_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_cancelCmd_presult__isset;

class SlaveServer_cancelCmd_presult {
 public:


  virtual ~SlaveServer_cancelCmd_presult() noexcept;
   ::CancelCmdResp* success;

  _SlaveServer_cancelCmd_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_getProbAmp_args__isset {
  _SlaveServer_getProbAmp_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_getProbAmp_args__isset;

class SlaveServer_getProbAmp_args {
 public:

  SlaveServer_getProbAmp_args(const SlaveServer_getProbAmp_args&);
  SlaveServer_getProbAmp_args& operator=(const SlaveServer_getProbAmp_args&);
  SlaveServer_getProbAmp_args() noexcept {
  }

  virtual ~SlaveServer_getProbAmp_args() noexcept;
   ::GetProbAmpReq req;

  _SlaveServer_getProbAmp_args__isset __isset;

  void __set_req(const  ::GetProbAmpReq& val);

  bool operator == (const SlaveServer_getProbAmp_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getProbAmp_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getProbAmp_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_getProbAmp_pargs {
 public:


  virtual ~SlaveServer_getProbAmp_pargs() noexcept;
  const  ::GetProbAmpReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getProbAmp_result__isset {
  _SlaveServer_getProbAmp_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getProbAmp_result__isset;

class SlaveServer_getProbAmp_result {
 public:

  SlaveServer_getProbAmp_result(const SlaveServer_getProbAmp_result&);
  SlaveServer_getProbAmp_result& operator=(const SlaveServer_getProbAmp_result&);
  SlaveServer_getProbAmp_result() noexcept {
  }

  virtual ~SlaveServer_getProbAmp_result() noexcept;
   ::GetProbAmpResp success;

  _SlaveServer_getProbAmp_result__isset __isset;

  void __set_success(const  ::GetProbAmpResp& val);

  bool operator == (const SlaveServer_getProbAmp_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getProbAmp_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getProbAmp_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getProbAmp_presult__isset {
  _SlaveServer_getProbAmp_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getProbAmp_presult__isset;

class SlaveServer_getProbAmp_presult {
 public:


  virtual ~SlaveServer_getProbAmp_presult() noexcept;
   ::GetProbAmpResp* success;

  _SlaveServer_getProbAmp_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_getProbOfOutcome_args__isset {
  _SlaveServer_getProbOfOutcome_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_getProbOfOutcome_args__isset;

class SlaveServer_getProbOfOutcome_args {
 public:

  SlaveServer_getProbOfOutcome_args(const SlaveServer_getProbOfOutcome_args&);
  SlaveServer_getProbOfOutcome_args& operator=(const SlaveServer_getProbOfOutcome_args&);
  SlaveServer_getProbOfOutcome_args() noexcept {
  }

  virtual ~SlaveServer_getProbOfOutcome_args() noexcept;
   ::GetProbOfOutcomeReq req;

  _SlaveServer_getProbOfOutcome_args__isset __isset;

  void __set_req(const  ::GetProbOfOutcomeReq& val);

  bool operator == (const SlaveServer_getProbOfOutcome_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getProbOfOutcome_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getProbOfOutcome_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_getProbOfOutcome_pargs {
 public:


  virtual ~SlaveServer_getProbOfOutcome_pargs() noexcept;
  const  ::GetProbOfOutcomeReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getProbOfOutcome_result__isset {
  _SlaveServer_getProbOfOutcome_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getProbOfOutcome_result__isset;

class SlaveServer_getProbOfOutcome_result {
 public:

  SlaveServer_getProbOfOutcome_result(const SlaveServer_getProbOfOutcome_result&);
  SlaveServer_getProbOfOutcome_result& operator=(const SlaveServer_getProbOfOutcome_result&);
  SlaveServer_getProbOfOutcome_result() noexcept {
  }

  virtual ~SlaveServer_getProbOfOutcome_result() noexcept;
   ::GetProbOfOutcomeResp success;

  _SlaveServer_getProbOfOutcome_result__isset __isset;

  void __set_success(const  ::GetProbOfOutcomeResp& val);

  bool operator == (const SlaveServer_getProbOfOutcome_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getProbOfOutcome_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getProbOfOutcome_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getProbOfOutcome_presult__isset {
  _SlaveServer_getProbOfOutcome_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getProbOfOutcome_presult__isset;

class SlaveServer_getProbOfOutcome_presult {
 public:


  virtual ~SlaveServer_getProbOfOutcome_presult() noexcept;
   ::GetProbOfOutcomeResp* success;

  _SlaveServer_getProbOfOutcome_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_getProbOfAllOutcome_args__isset {
  _SlaveServer_getProbOfAllOutcome_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_getProbOfAllOutcome_args__isset;

class SlaveServer_getProbOfAllOutcome_args {
 public:

  SlaveServer_getProbOfAllOutcome_args(const SlaveServer_getProbOfAllOutcome_args&);
  SlaveServer_getProbOfAllOutcome_args& operator=(const SlaveServer_getProbOfAllOutcome_args&);
  SlaveServer_getProbOfAllOutcome_args() noexcept {
  }

  virtual ~SlaveServer_getProbOfAllOutcome_args() noexcept;
   ::GetProbOfAllOutcomReq req;

  _SlaveServer_getProbOfAllOutcome_args__isset __isset;

  void __set_req(const  ::GetProbOfAllOutcomReq& val);

  bool operator == (const SlaveServer_getProbOfAllOutcome_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getProbOfAllOutcome_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getProbOfAllOutcome_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_getProbOfAllOutcome_pargs {
 public:


  virtual ~SlaveServer_getProbOfAllOutcome_pargs() noexcept;
  const  ::GetProbOfAllOutcomReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getProbOfAllOutcome_result__isset {
  _SlaveServer_getProbOfAllOutcome_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getProbOfAllOutcome_result__isset;

class SlaveServer_getProbOfAllOutcome_result {
 public:

  SlaveServer_getProbOfAllOutcome_result(const SlaveServer_getProbOfAllOutcome_result&);
  SlaveServer_getProbOfAllOutcome_result& operator=(const SlaveServer_getProbOfAllOutcome_result&);
  SlaveServer_getProbOfAllOutcome_result() noexcept {
  }

  virtual ~SlaveServer_getProbOfAllOutcome_result() noexcept;
   ::GetProbOfAllOutcomResp success;

  _SlaveServer_getProbOfAllOutcome_result__isset __isset;

  void __set_success(const  ::GetProbOfAllOutcomResp& val);

  bool operator == (const SlaveServer_getProbOfAllOutcome_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getProbOfAllOutcome_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getProbOfAllOutcome_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getProbOfAllOutcome_presult__isset {
  _SlaveServer_getProbOfAllOutcome_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getProbOfAllOutcome_presult__isset;

class SlaveServer_getProbOfAllOutcome_presult {
 public:


  virtual ~SlaveServer_getProbOfAllOutcome_presult() noexcept;
   ::GetProbOfAllOutcomResp* success;

  _SlaveServer_getProbOfAllOutcome_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_getAllState_args__isset {
  _SlaveServer_getAllState_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_getAllState_args__isset;

class SlaveServer_getAllState_args {
 public:

  SlaveServer_getAllState_args(const SlaveServer_getAllState_args&);
  SlaveServer_getAllState_args& operator=(const SlaveServer_getAllState_args&);
  SlaveServer_getAllState_args() noexcept {
  }

  virtual ~SlaveServer_getAllState_args() noexcept;
   ::GetAllStateReq req;

  _SlaveServer_getAllState_args__isset __isset;

  void __set_req(const  ::GetAllStateReq& val);

  bool operator == (const SlaveServer_getAllState_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getAllState_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getAllState_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_getAllState_pargs {
 public:


  virtual ~SlaveServer_getAllState_pargs() noexcept;
  const  ::GetAllStateReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getAllState_result__isset {
  _SlaveServer_getAllState_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getAllState_result__isset;

class SlaveServer_getAllState_result {
 public:

  SlaveServer_getAllState_result(const SlaveServer_getAllState_result&);
  SlaveServer_getAllState_result& operator=(const SlaveServer_getAllState_result&);
  SlaveServer_getAllState_result() noexcept {
  }

  virtual ~SlaveServer_getAllState_result() noexcept;
   ::GetAllStateResp success;

  _SlaveServer_getAllState_result__isset __isset;

  void __set_success(const  ::GetAllStateResp& val);

  bool operator == (const SlaveServer_getAllState_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getAllState_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getAllState_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getAllState_presult__isset {
  _SlaveServer_getAllState_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getAllState_presult__isset;

class SlaveServer_getAllState_presult {
 public:


  virtual ~SlaveServer_getAllState_presult() noexcept;
   ::GetAllStateResp* success;

  _SlaveServer_getAllState_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_run_args__isset {
  _SlaveServer_run_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_run_args__isset;

class SlaveServer_run_args {
 public:

  SlaveServer_run_args(const SlaveServer_run_args&);
  SlaveServer_run_args& operator=(const SlaveServer_run_args&);
  SlaveServer_run_args() noexcept {
  }

  virtual ~SlaveServer_run_args() noexcept;
   ::RunCircuitReq req;

  _SlaveServer_run_args__isset __isset;

  void __set_req(const  ::RunCircuitReq& val);

  bool operator == (const SlaveServer_run_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_run_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_run_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_run_pargs {
 public:


  virtual ~SlaveServer_run_pargs() noexcept;
  const  ::RunCircuitReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_run_result__isset {
  _SlaveServer_run_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_run_result__isset;

class SlaveServer_run_result {
 public:

  SlaveServer_run_result(const SlaveServer_run_result&);
  SlaveServer_run_result& operator=(const SlaveServer_run_result&);
  SlaveServer_run_result() noexcept {
  }

  virtual ~SlaveServer_run_result() noexcept;
   ::RunCircuitResp success;

  _SlaveServer_run_result__isset __isset;

  void __set_success(const  ::RunCircuitResp& val);

  bool operator == (const SlaveServer_run_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_run_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_run_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_run_presult__isset {
  _SlaveServer_run_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_run_presult__isset;

class SlaveServer_run_presult {
 public:


  virtual ~SlaveServer_run_presult() noexcept;
   ::RunCircuitResp* success;

  _SlaveServer_run_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_applyQFT_args__isset {
  _SlaveServer_applyQFT_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_applyQFT_args__isset;

class SlaveServer_applyQFT_args {
 public:

  SlaveServer_applyQFT_args(const SlaveServer_applyQFT_args&);
  SlaveServer_applyQFT_args& operator=(const SlaveServer_applyQFT_args&);
  SlaveServer_applyQFT_args() noexcept {
  }

  virtual ~SlaveServer_applyQFT_args() noexcept;
   ::ApplyQFTReq req;

  _SlaveServer_applyQFT_args__isset __isset;

  void __set_req(const  ::ApplyQFTReq& val);

  bool operator == (const SlaveServer_applyQFT_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_applyQFT_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_applyQFT_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_applyQFT_pargs {
 public:


  virtual ~SlaveServer_applyQFT_pargs() noexcept;
  const  ::ApplyQFTReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_applyQFT_result__isset {
  _SlaveServer_applyQFT_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_applyQFT_result__isset;

class SlaveServer_applyQFT_result {
 public:

  SlaveServer_applyQFT_result(const SlaveServer_applyQFT_result&);
  SlaveServer_applyQFT_result& operator=(const SlaveServer_applyQFT_result&);
  SlaveServer_applyQFT_result() noexcept {
  }

  virtual ~SlaveServer_applyQFT_result() noexcept;
   ::ApplyQFTResp success;

  _SlaveServer_applyQFT_result__isset __isset;

  void __set_success(const  ::ApplyQFTResp& val);

  bool operator == (const SlaveServer_applyQFT_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_applyQFT_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_applyQFT_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_applyQFT_presult__isset {
  _SlaveServer_applyQFT_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_applyQFT_presult__isset;

class SlaveServer_applyQFT_presult {
 public:


  virtual ~SlaveServer_applyQFT_presult() noexcept;
   ::ApplyQFTResp* success;

  _SlaveServer_applyQFT_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_applyFullQFT_args__isset {
  _SlaveServer_applyFullQFT_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_applyFullQFT_args__isset;

class SlaveServer_applyFullQFT_args {
 public:

  SlaveServer_applyFullQFT_args(const SlaveServer_applyFullQFT_args&);
  SlaveServer_applyFullQFT_args& operator=(const SlaveServer_applyFullQFT_args&);
  SlaveServer_applyFullQFT_args() noexcept {
  }

  virtual ~SlaveServer_applyFullQFT_args() noexcept;
   ::ApplyFullQFTReq req;

  _SlaveServer_applyFullQFT_args__isset __isset;

  void __set_req(const  ::ApplyFullQFTReq& val);

  bool operator == (const SlaveServer_applyFullQFT_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_applyFullQFT_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_applyFullQFT_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_applyFullQFT_pargs {
 public:


  virtual ~SlaveServer_applyFullQFT_pargs() noexcept;
  const  ::ApplyFullQFTReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_applyFullQFT_result__isset {
  _SlaveServer_applyFullQFT_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_applyFullQFT_result__isset;

class SlaveServer_applyFullQFT_result {
 public:

  SlaveServer_applyFullQFT_result(const SlaveServer_applyFullQFT_result&);
  SlaveServer_applyFullQFT_result& operator=(const SlaveServer_applyFullQFT_result&);
  SlaveServer_applyFullQFT_result() noexcept {
  }

  virtual ~SlaveServer_applyFullQFT_result() noexcept;
   ::ApplyFullQFTResp success;

  _SlaveServer_applyFullQFT_result__isset __isset;

  void __set_success(const  ::ApplyFullQFTResp& val);

  bool operator == (const SlaveServer_applyFullQFT_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_applyFullQFT_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_applyFullQFT_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_applyFullQFT_presult__isset {
  _SlaveServer_applyFullQFT_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_applyFullQFT_presult__isset;

class SlaveServer_applyFullQFT_presult {
 public:


  virtual ~SlaveServer_applyFullQFT_presult() noexcept;
   ::ApplyFullQFTResp* success;

  _SlaveServer_applyFullQFT_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_getExpecPauliProd_args__isset {
  _SlaveServer_getExpecPauliProd_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_getExpecPauliProd_args__isset;

class SlaveServer_getExpecPauliProd_args {
 public:

  SlaveServer_getExpecPauliProd_args(const SlaveServer_getExpecPauliProd_args&);
  SlaveServer_getExpecPauliProd_args& operator=(const SlaveServer_getExpecPauliProd_args&);
  SlaveServer_getExpecPauliProd_args() noexcept {
  }

  virtual ~SlaveServer_getExpecPauliProd_args() noexcept;
   ::GetExpecPauliProdReq req;

  _SlaveServer_getExpecPauliProd_args__isset __isset;

  void __set_req(const  ::GetExpecPauliProdReq& val);

  bool operator == (const SlaveServer_getExpecPauliProd_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getExpecPauliProd_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getExpecPauliProd_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_getExpecPauliProd_pargs {
 public:


  virtual ~SlaveServer_getExpecPauliProd_pargs() noexcept;
  const  ::GetExpecPauliProdReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getExpecPauliProd_result__isset {
  _SlaveServer_getExpecPauliProd_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getExpecPauliProd_result__isset;

class SlaveServer_getExpecPauliProd_result {
 public:

  SlaveServer_getExpecPauliProd_result(const SlaveServer_getExpecPauliProd_result&);
  SlaveServer_getExpecPauliProd_result& operator=(const SlaveServer_getExpecPauliProd_result&);
  SlaveServer_getExpecPauliProd_result() noexcept {
  }

  virtual ~SlaveServer_getExpecPauliProd_result() noexcept;
   ::GetExpecPauliProdResp success;

  _SlaveServer_getExpecPauliProd_result__isset __isset;

  void __set_success(const  ::GetExpecPauliProdResp& val);

  bool operator == (const SlaveServer_getExpecPauliProd_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getExpecPauliProd_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getExpecPauliProd_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getExpecPauliProd_presult__isset {
  _SlaveServer_getExpecPauliProd_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getExpecPauliProd_presult__isset;

class SlaveServer_getExpecPauliProd_presult {
 public:


  virtual ~SlaveServer_getExpecPauliProd_presult() noexcept;
   ::GetExpecPauliProdResp* success;

  _SlaveServer_getExpecPauliProd_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveServer_getExpecPauliSum_args__isset {
  _SlaveServer_getExpecPauliSum_args__isset() : req(false) {}
  bool req :1;
} _SlaveServer_getExpecPauliSum_args__isset;

class SlaveServer_getExpecPauliSum_args {
 public:

  SlaveServer_getExpecPauliSum_args(const SlaveServer_getExpecPauliSum_args&);
  SlaveServer_getExpecPauliSum_args& operator=(const SlaveServer_getExpecPauliSum_args&);
  SlaveServer_getExpecPauliSum_args() noexcept {
  }

  virtual ~SlaveServer_getExpecPauliSum_args() noexcept;
   ::GetExpecPauliSumReq req;

  _SlaveServer_getExpecPauliSum_args__isset __isset;

  void __set_req(const  ::GetExpecPauliSumReq& val);

  bool operator == (const SlaveServer_getExpecPauliSum_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getExpecPauliSum_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getExpecPauliSum_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveServer_getExpecPauliSum_pargs {
 public:


  virtual ~SlaveServer_getExpecPauliSum_pargs() noexcept;
  const  ::GetExpecPauliSumReq* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getExpecPauliSum_result__isset {
  _SlaveServer_getExpecPauliSum_result__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getExpecPauliSum_result__isset;

class SlaveServer_getExpecPauliSum_result {
 public:

  SlaveServer_getExpecPauliSum_result(const SlaveServer_getExpecPauliSum_result&);
  SlaveServer_getExpecPauliSum_result& operator=(const SlaveServer_getExpecPauliSum_result&);
  SlaveServer_getExpecPauliSum_result() noexcept {
  }

  virtual ~SlaveServer_getExpecPauliSum_result() noexcept;
   ::GetExpecPauliSumResp success;

  _SlaveServer_getExpecPauliSum_result__isset __isset;

  void __set_success(const  ::GetExpecPauliSumResp& val);

  bool operator == (const SlaveServer_getExpecPauliSum_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveServer_getExpecPauliSum_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveServer_getExpecPauliSum_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveServer_getExpecPauliSum_presult__isset {
  _SlaveServer_getExpecPauliSum_presult__isset() : success(false) {}
  bool success :1;
} _SlaveServer_getExpecPauliSum_presult__isset;

class SlaveServer_getExpecPauliSum_presult {
 public:


  virtual ~SlaveServer_getExpecPauliSum_presult() noexcept;
   ::GetExpecPauliSumResp* success;

  _SlaveServer_getExpecPauliSum_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class SlaveServerClient : virtual public SlaveServerIf {
 public:
  SlaveServerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SlaveServerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void initQubits( ::InitQubitsResp& _return, const  ::InitQubitsReq& req) override;
  void send_initQubits(const  ::InitQubitsReq& req);
  void recv_initQubits( ::InitQubitsResp& _return);
  void sendCircuitCmd( ::SendCircuitCmdResp& _return, const  ::SendCircuitCmdReq& req) override;
  void send_sendCircuitCmd(const  ::SendCircuitCmdReq& req);
  void recv_sendCircuitCmd( ::SendCircuitCmdResp& _return);
  void cancelCmd( ::CancelCmdResp& _return, const  ::CancelCmdReq& req) override;
  void send_cancelCmd(const  ::CancelCmdReq& req);
  void recv_cancelCmd( ::CancelCmdResp& _return);
  void getProbAmp( ::GetProbAmpResp& _return, const  ::GetProbAmpReq& req) override;
  void send_getProbAmp(const  ::GetProbAmpReq& req);
  void recv_getProbAmp( ::GetProbAmpResp& _return);
  void getProbOfOutcome( ::GetProbOfOutcomeResp& _return, const  ::GetProbOfOutcomeReq& req) override;
  void send_getProbOfOutcome(const  ::GetProbOfOutcomeReq& req);
  void recv_getProbOfOutcome( ::GetProbOfOutcomeResp& _return);
  void getProbOfAllOutcome( ::GetProbOfAllOutcomResp& _return, const  ::GetProbOfAllOutcomReq& req) override;
  void send_getProbOfAllOutcome(const  ::GetProbOfAllOutcomReq& req);
  void recv_getProbOfAllOutcome( ::GetProbOfAllOutcomResp& _return);
  void getAllState( ::GetAllStateResp& _return, const  ::GetAllStateReq& req) override;
  void send_getAllState(const  ::GetAllStateReq& req);
  void recv_getAllState( ::GetAllStateResp& _return);
  void run( ::RunCircuitResp& _return, const  ::RunCircuitReq& req) override;
  void send_run(const  ::RunCircuitReq& req);
  void recv_run( ::RunCircuitResp& _return);
  void applyQFT( ::ApplyQFTResp& _return, const  ::ApplyQFTReq& req) override;
  void send_applyQFT(const  ::ApplyQFTReq& req);
  void recv_applyQFT( ::ApplyQFTResp& _return);
  void applyFullQFT( ::ApplyFullQFTResp& _return, const  ::ApplyFullQFTReq& req) override;
  void send_applyFullQFT(const  ::ApplyFullQFTReq& req);
  void recv_applyFullQFT( ::ApplyFullQFTResp& _return);
  void getExpecPauliProd( ::GetExpecPauliProdResp& _return, const  ::GetExpecPauliProdReq& req) override;
  void send_getExpecPauliProd(const  ::GetExpecPauliProdReq& req);
  void recv_getExpecPauliProd( ::GetExpecPauliProdResp& _return);
  void getExpecPauliSum( ::GetExpecPauliSumResp& _return, const  ::GetExpecPauliSumReq& req) override;
  void send_getExpecPauliSum(const  ::GetExpecPauliSumReq& req);
  void recv_getExpecPauliSum( ::GetExpecPauliSumResp& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SlaveServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<SlaveServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (SlaveServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_initQubits(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_sendCircuitCmd(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_cancelCmd(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getProbAmp(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getProbOfOutcome(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getProbOfAllOutcome(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getAllState(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_run(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_applyQFT(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_applyFullQFT(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getExpecPauliProd(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getExpecPauliSum(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SlaveServerProcessor(::std::shared_ptr<SlaveServerIf> iface) :
    iface_(iface) {
    processMap_["initQubits"] = &SlaveServerProcessor::process_initQubits;
    processMap_["sendCircuitCmd"] = &SlaveServerProcessor::process_sendCircuitCmd;
    processMap_["cancelCmd"] = &SlaveServerProcessor::process_cancelCmd;
    processMap_["getProbAmp"] = &SlaveServerProcessor::process_getProbAmp;
    processMap_["getProbOfOutcome"] = &SlaveServerProcessor::process_getProbOfOutcome;
    processMap_["getProbOfAllOutcome"] = &SlaveServerProcessor::process_getProbOfAllOutcome;
    processMap_["getAllState"] = &SlaveServerProcessor::process_getAllState;
    processMap_["run"] = &SlaveServerProcessor::process_run;
    processMap_["applyQFT"] = &SlaveServerProcessor::process_applyQFT;
    processMap_["applyFullQFT"] = &SlaveServerProcessor::process_applyFullQFT;
    processMap_["getExpecPauliProd"] = &SlaveServerProcessor::process_getExpecPauliProd;
    processMap_["getExpecPauliSum"] = &SlaveServerProcessor::process_getExpecPauliSum;
  }

  virtual ~SlaveServerProcessor() {}
};

class SlaveServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  SlaveServerProcessorFactory(const ::std::shared_ptr< SlaveServerIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< SlaveServerIfFactory > handlerFactory_;
};

class SlaveServerMultiface : virtual public SlaveServerIf {
 public:
  SlaveServerMultiface(std::vector<std::shared_ptr<SlaveServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SlaveServerMultiface() {}
 protected:
  std::vector<std::shared_ptr<SlaveServerIf> > ifaces_;
  SlaveServerMultiface() {}
  void add(::std::shared_ptr<SlaveServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void initQubits( ::InitQubitsResp& _return, const  ::InitQubitsReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->initQubits(_return, req);
    }
    ifaces_[i]->initQubits(_return, req);
    return;
  }

  void sendCircuitCmd( ::SendCircuitCmdResp& _return, const  ::SendCircuitCmdReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sendCircuitCmd(_return, req);
    }
    ifaces_[i]->sendCircuitCmd(_return, req);
    return;
  }

  void cancelCmd( ::CancelCmdResp& _return, const  ::CancelCmdReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->cancelCmd(_return, req);
    }
    ifaces_[i]->cancelCmd(_return, req);
    return;
  }

  void getProbAmp( ::GetProbAmpResp& _return, const  ::GetProbAmpReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getProbAmp(_return, req);
    }
    ifaces_[i]->getProbAmp(_return, req);
    return;
  }

  void getProbOfOutcome( ::GetProbOfOutcomeResp& _return, const  ::GetProbOfOutcomeReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getProbOfOutcome(_return, req);
    }
    ifaces_[i]->getProbOfOutcome(_return, req);
    return;
  }

  void getProbOfAllOutcome( ::GetProbOfAllOutcomResp& _return, const  ::GetProbOfAllOutcomReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getProbOfAllOutcome(_return, req);
    }
    ifaces_[i]->getProbOfAllOutcome(_return, req);
    return;
  }

  void getAllState( ::GetAllStateResp& _return, const  ::GetAllStateReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getAllState(_return, req);
    }
    ifaces_[i]->getAllState(_return, req);
    return;
  }

  void run( ::RunCircuitResp& _return, const  ::RunCircuitReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->run(_return, req);
    }
    ifaces_[i]->run(_return, req);
    return;
  }

  void applyQFT( ::ApplyQFTResp& _return, const  ::ApplyQFTReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->applyQFT(_return, req);
    }
    ifaces_[i]->applyQFT(_return, req);
    return;
  }

  void applyFullQFT( ::ApplyFullQFTResp& _return, const  ::ApplyFullQFTReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->applyFullQFT(_return, req);
    }
    ifaces_[i]->applyFullQFT(_return, req);
    return;
  }

  void getExpecPauliProd( ::GetExpecPauliProdResp& _return, const  ::GetExpecPauliProdReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getExpecPauliProd(_return, req);
    }
    ifaces_[i]->getExpecPauliProd(_return, req);
    return;
  }

  void getExpecPauliSum( ::GetExpecPauliSumResp& _return, const  ::GetExpecPauliSumReq& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getExpecPauliSum(_return, req);
    }
    ifaces_[i]->getExpecPauliSum(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class SlaveServerConcurrentClient : virtual public SlaveServerIf {
 public:
  SlaveServerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  SlaveServerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void initQubits( ::InitQubitsResp& _return, const  ::InitQubitsReq& req) override;
  int32_t send_initQubits(const  ::InitQubitsReq& req);
  void recv_initQubits( ::InitQubitsResp& _return, const int32_t seqid);
  void sendCircuitCmd( ::SendCircuitCmdResp& _return, const  ::SendCircuitCmdReq& req) override;
  int32_t send_sendCircuitCmd(const  ::SendCircuitCmdReq& req);
  void recv_sendCircuitCmd( ::SendCircuitCmdResp& _return, const int32_t seqid);
  void cancelCmd( ::CancelCmdResp& _return, const  ::CancelCmdReq& req) override;
  int32_t send_cancelCmd(const  ::CancelCmdReq& req);
  void recv_cancelCmd( ::CancelCmdResp& _return, const int32_t seqid);
  void getProbAmp( ::GetProbAmpResp& _return, const  ::GetProbAmpReq& req) override;
  int32_t send_getProbAmp(const  ::GetProbAmpReq& req);
  void recv_getProbAmp( ::GetProbAmpResp& _return, const int32_t seqid);
  void getProbOfOutcome( ::GetProbOfOutcomeResp& _return, const  ::GetProbOfOutcomeReq& req) override;
  int32_t send_getProbOfOutcome(const  ::GetProbOfOutcomeReq& req);
  void recv_getProbOfOutcome( ::GetProbOfOutcomeResp& _return, const int32_t seqid);
  void getProbOfAllOutcome( ::GetProbOfAllOutcomResp& _return, const  ::GetProbOfAllOutcomReq& req) override;
  int32_t send_getProbOfAllOutcome(const  ::GetProbOfAllOutcomReq& req);
  void recv_getProbOfAllOutcome( ::GetProbOfAllOutcomResp& _return, const int32_t seqid);
  void getAllState( ::GetAllStateResp& _return, const  ::GetAllStateReq& req) override;
  int32_t send_getAllState(const  ::GetAllStateReq& req);
  void recv_getAllState( ::GetAllStateResp& _return, const int32_t seqid);
  void run( ::RunCircuitResp& _return, const  ::RunCircuitReq& req) override;
  int32_t send_run(const  ::RunCircuitReq& req);
  void recv_run( ::RunCircuitResp& _return, const int32_t seqid);
  void applyQFT( ::ApplyQFTResp& _return, const  ::ApplyQFTReq& req) override;
  int32_t send_applyQFT(const  ::ApplyQFTReq& req);
  void recv_applyQFT( ::ApplyQFTResp& _return, const int32_t seqid);
  void applyFullQFT( ::ApplyFullQFTResp& _return, const  ::ApplyFullQFTReq& req) override;
  int32_t send_applyFullQFT(const  ::ApplyFullQFTReq& req);
  void recv_applyFullQFT( ::ApplyFullQFTResp& _return, const int32_t seqid);
  void getExpecPauliProd( ::GetExpecPauliProdResp& _return, const  ::GetExpecPauliProdReq& req) override;
  int32_t send_getExpecPauliProd(const  ::GetExpecPauliProdReq& req);
  void recv_getExpecPauliProd( ::GetExpecPauliProdResp& _return, const int32_t seqid);
  void getExpecPauliSum( ::GetExpecPauliSumResp& _return, const  ::GetExpecPauliSumReq& req) override;
  int32_t send_getExpecPauliSum(const  ::GetExpecPauliSumReq& req);
  void recv_getExpecPauliSum( ::GetExpecPauliSumResp& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
