/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ecode_constants.h"



const ecodeConstants g_ecode_constants;

ecodeConstants::ecodeConstants() {
  ErrMsg.insert(std::make_pair((ErrCode::type)4, "异常"));
  ErrMsg.insert(std::make_pair((ErrCode::type)2, "不合法参数"));
  ErrMsg.insert(std::make_pair((ErrCode::type)6, "存在"));
  ErrMsg.insert(std::make_pair((ErrCode::type)7, "缓存中"));
  ErrMsg.insert(std::make_pair((ErrCode::type)8, "内存不足"));
  ErrMsg.insert(std::make_pair((ErrCode::type)5, "不存在"));
  ErrMsg.insert(std::make_pair((ErrCode::type)9, "未初始化"));
  ErrMsg.insert(std::make_pair((ErrCode::type)10, "机器未注册"));
  ErrMsg.insert(std::make_pair((ErrCode::type)11, "无可用的资源"));
  ErrMsg.insert(std::make_pair((ErrCode::type)1, "未知错误"));
  ErrMsg.insert(std::make_pair((ErrCode::type)12, "数据解析异常"));
  ErrMsg.insert(std::make_pair((ErrCode::type)0, "成功"));
  ErrMsg.insert(std::make_pair((ErrCode::type)3, "超时"));

}



