log:
  logLevel: 0
  logPath: /var/log
  logNamePrefix: qusprout
common:
  verbose: 0
rpc:
  listenPort: 9091
  sendTimeout: 0
  recvTimeout: 0
task:
  cleanTaskInterval: 150
  cleanTaskTimeout:
    - taskState: 0
      timeout: 300
    - taskState: 1
      timeout: 300
    - taskState: 2
      timeout: 300
    - taskState: 3
      timeout: 300
    - taskState: 4
      timeout: 300
    - taskState: 5
      timeout: 300
    - taskState: 6
      timeout: 1
client:
  clientConnTimeout: 300000
  clientSendTimeout: 300000
  clientRecvTimeout: 300000
quroot:
  enable: 0
  port: 8002
  addr: 127.0.0.1
  qurootHeartInterval: 3
cap:
  - deviceType: cpu
    supGate: h,measure,p,cp,r,rx,ry,rz,rxx,ryy,rzz,x,y,z,s,t,sdg,tdg,sqrtx,sqrtswap,swap,cnot,cx,cy,cz,u3,u2,u1,crx,cry,crz,x1,y1,z1,cu1,cu3,u,cu,cr,iswap,id,ch,sqrtxdg,csqrtx,cswap,ph
http:
  listenHttpPort: 9093
  httpThreadNum: 5
quwork:
  quworkBinPath: /usr/local/bin
  quworkBinName: quwork
  quworkGpuBinName: quwork-gpu
  quworkConfigPath: /usr/local/etc/qusprout
  quworkConfigName: quwork.yaml
  waitRpcTimeout: 60
  waitMpiRpcTimeout: 120